# Required Env Vars
# NPM_TOKEN

# Main Config
version: 2

job_common: &job_common
  docker:
    - image: circleci/node:carbon-browsers

# Main Config
jobs:
  build:
    <<: *job_common
    environment:
      NODE_ENV: "test"
      SAUCE_CONNECT_DOWNLOAD_ON_INSTALL: true
      ACL_SERVICE_URL: 'https://acl-intb.ciscospark.com/acl/api/v1'
      ATLAS_SERVICE_URL: 'https://atlas-intb.ciscospark.com/admin/api/v1'
      CONVERSATION_SERVICE: 'https://conversation-intb.ciscospark.com/conversation/api/v1'
      ENCRYPTION_SERVICE_URL: 'https://encryption-intb.ciscospark.com/encryption/api/v1'
      HYDRA_SERVICE_URL: 'https://apialpha.ciscospark.com/v1/'
      IDBROKER_BASE_URL: 'https://idbrokerbts.webex.com/'
      IDENTITY_BASE_URL: 'https://identitybts.webex.com/'
      U2C_SERVICE_URL: 'https://u2c-intb.ciscospark.com/u2c/api/v1'
      WDM_SERVICE_URL: 'https://wdm-intb.ciscospark.com/wdm/api/v1'
      WHISTLER_API_SERVICE_URL: 'https://whistler.onint.ciscospark.com/api/v1'
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          name: "Update NPM and Install dependencies"
          command: sudo npm install -g npm@6
      - run:
          name: "Install dependencies"
          command: npm ci
      # - run:
      #     name: "Run linting"
      #     command: npm run lint:ci
      - run:
          name: "Build all packages"
          command: npm run build
      - run:
            name: "Test modified packages"
            command: npm run test:github
      - run:
          name: "Test Samples"
          command: npm run samples:test



