# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cisco Webex JS SDK
baseurl: "/spark-js-sdk"
permalink: /:categories/:title/
url: "https://webex.github.io/"

# Set future: true to print posts with future dates. Basically, this is a hack
# to use fake post dates to control order of examples
future: true

# Use the same settings that GitHub Pages will use
safe: true

# Build settings
markdown: kramdown
syntax_highlighter: rouge

kramdown:
  input: GFM

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-minimal