toc:
  - name: spark-js-sdk
    file: ciscospark.md
  - CiscoSpark
  - name: Authorization
  - AuthorizationBrowser
  - AuthorizationNode
  - name: Calling
  - Phone
  - PhoneConfig
  - Call
  - CallMemberships
  - CallMembership
  - StatsStream
  - StatsFilter
  - Meetings
  - name: Resources
    description: |
      These are the resources provided by CiscoSpark instances for interacting with our [developer API](https://developer.webex.com/getting-started.html)
  - Memberships
  - Messages
  - People
  - Rooms
  - Teams
  - TeamMemberships
  - Webhooks
  # - Organizations
  # - Licenses
  # - Roles
  - name: Logging
  - Logger
  - LoggerConfig
  - name: Types
    description: |
      The following typedefs describes the responses of the various API calls.
  - FeedbackObject
  - MembershipObject
  - MessageObject
  - PersonObject
  - RoomObject
  - TeamObject
  - TeamMembershipObject
  - WebhookObject
  - email
  - isoDate
